// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  genKitSidebar: [
    'intro',
    {
      type: 'category',
      label: '👜 获取服务器',
      items: [
        'server/join',
        {
          type: 'category',
          label: '🚜 自行搭建',
          items: [
            'server/create/get',
            {
              type: 'category',
              label: '⚒️ 部署服务端',
              items: [
                'server/create/deploy/windows',
                'server/create/deploy/linux',
                'server/create/deploy/macos',
                {
                  type: 'category',
                  label: '🤖 安卓',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'server/create/deploy/android'
                    }
                  ],
                },
                'server/create/deploy/click-to-run',
                'server/create/deploy/fastrun-debian-ios'
              ],
            },
          ]
        },
      ],
    },
    {
      type: 'category',
      label: '🔗 加入服务器',
      items: [
        'client/oneclick',
        'client/proxy',
        'client/patch',
      ]
    },
    {
      type: 'category',
      label: '📃 文件释义',
      items: [
        {
          type: 'autogenerated',
          dirName: 'file-interpretation',
        }
      ],
    },
    {
      type: 'category',
      label: '❓ FAQ',
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq',
        }
      ],
    },
    {
      type: 'category',
      label: '📌 其他',
      items: [
        {
          type: 'autogenerated',
          dirName: 'other',
        }
      ],
    },
    'about'
  ]
};

module.exports = sidebars;
