// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  genKitSidebar: [
    'about',
    {
      type: 'category',
      label: '🚜 快速开始',
      items: [
        'quick-start/get-server',
        {
          type: 'category',
          label: '⚒️ 部署',
          items: [
            'quick-start/deploy/linux',
            'quick-start/deploy/macos',
            {
              type: 'category',
              label: '🤖 安卓',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'quick-start/deploy/android'
                }
              ],
            },
            'quick-start/deploy/windows',
            'quick-start/deploy/click-to-run',
            'quick-start/deploy/fastrun-debian-ios'
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📃 文件释义',
      items: [
        {
          type: 'autogenerated',
          dirName: 'file-interpretation',
        }
      ],
    },
    {
      type: 'category',
      label: '❓ FAQ',
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq',
        }
      ],
    }
  ]
};

module.exports = sidebars;
