/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  genKitSidebar: [
    'about',
    {
      type: 'category',
      label: '快速开始',
      items: [
        {
          type: 'autogenerated',
          dirName: 'quick-start', // Generate sidebar slice from docs/tutorials/easy
        }
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq', // Generate sidebar slice from docs/tutorials/easy
        }
      ],
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
